package com.financetracker.model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "transactions", indexes = {
    @Index(name = "idx_tx_user_date", columnList = "user_id, date"),
    @Index(name = "idx_tx_user_type_date", columnList = "user_id, type, date"),
    @Index(name = "idx_tx_user_active", columnList = "user_id, is_deleted, date"),
    @Index(name = "idx_tx_user_cat_date", columnList = "user_id, category_id, date"),
    @Index(name = "idx_tx_category", columnList = "category_id"),
    @Index(name = "idx_tx_account", columnList = "account_id"),
    @Index(name = "idx_tx_transfer", columnList = "transfer_id"),
    @Index(name = "idx_tx_merchant", columnList = "user_id, merchant")
})
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @Column(nullable = false)
    private LocalDate date;

    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal amount;

    // ISO 4217 code for orig. transaction currency (USD)
    @Builder.Default
    @Column(nullable = false, length = 10)
    private String currency = "USD";

    // Exchange rate from currency -> user base currency at transaction time, null = same currency
    @Column(precision = 16, scale = 8)
    private BigDecimal exchangeRate;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionType type;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    private Category category;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "account_id")
    private Account account;

    private String note;

    @Column(length = 200)
    private String merchant;

    @Column(length = 200)
    private String location;

    @Builder.Default
    @Enumerated(EnumType.STRING)
    private RecurType recur = RecurType.NONE;

    // Links legs between two accounts
    @Column(name = "transfer_id")
    private String transferId;

    // When or if generated by a RecurringRule references that rule's ID
    @Column(name = "recurring_rule_id", length = 36)
    private String recurringRuleId;

    @Builder.Default
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
        name = "transactions_tags",
        joinColumns = @JoinColumn(name = "transaction_id"),
        inverseJoinColumns = @JoinColumn(name = "tag_id")
    )
    private Set<Tag> tags = new HashSet<>();

    // Soft delete, row is kept for audit trail but excluded from all the business logic
    @Builder.Default
    @Column(nullable = false)
    private Boolean isDeleted = false;

    private LocalDateTime deletedAt;

    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    private LocalDateTime updatedAt;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    @JsonIgnore
    private User user;

    public BigDecimal signedAmount() {
        if (amount == null) return BigDecimal.ZERO;
        return type == TransactionType.INCOME ? amount : amount.negate();
    }
}
